#!/usr/bin/python
#import sys
from bottle import Bottle, abort, debug, request, route, run

from edu.artic.sspad.config import host
from edu.artic.sspad.modules.image import Image

debug(True)

@route('/resource/get/<uid>', method='GET')
def resourceGetByUid(uid):
	"""Retrieves a single image by UID."""
	pass

@route('/image', method='POST')
def imagePost():
	Image().postMethod()


#@route('/image/findByObjectPKey/<pkey>', method='GET')
#def findImagesByObjPKey(pkey):
#	"""Finds all the image nodes belonging to an object."""
#	pass


@route('/datastream', method='GET')
def findImageDStreams():
	"""Finds all the datastream nodes for an image node."""
	pass





run(host = host.app_host, port = host.app_port)
